apiVersion: apps/v1
kind: Deployment
metadata:
  name: student01-deployment
spec:
  selector:
    matchLabels:
      app: student01
  template:
    metadata:
      labels:
        app: student01
    spec:
      containers:
      - name: student01
        image: registry.tanzu.dk/ops2devops/student01:v1
