apiVersion: apps/v1
kind: Deployment
metadata:
  name: student01-deployment
  namespace: student01
spec:
  selector:
    matchLabels:
      app: student01
  template:
    metadata:
      labels:
        app: student01
    spec:
      containers:
      - name: student01
        image: registry.tanzu.dk/ops2devops/student01:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student01
spec:
  type: NodePort
  selector:
    app: student01
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011 # Remember to change to student number.

